vich_uploader:
    db_driver: orm

    mappings:
        email_attachment:
            uri_prefix: /uploads/attachments
            upload_destination: '%kernel.project_dir%/public/uploads/attachments'
            namer: Vich\UploaderBundle\Naming\OrignameNamer